# Generated by Django 4.0.3 on 2022-04-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text_name', models.CharField(blank=True, max_length=30, null=True)),
                ('message', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='user is active')),
                ('is_deleted', models.BooleanField(default=False, help_text='to delete the user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
